class queries:
    insert_into_student = "INSERT INTO STUDENT VALUES('%s', '%s', '%s','%s','%s','%s')"
    borrow_book_status_stu = "SELECT sb_id from student_borrow where sb_bid = '%s' and sb_return =0"
    borrow_book_status_teach = "SELECT tb_id from teacher_borrow where tb_bid = '%s' and tb_return = 0"
    borrow_book_type = "select b_type from book where b_id = %s"
    borrow_student_limit = "select * from student_borrow where sb_id = '%s'"
    insert_into_student_borrow = "Insert into student_borrow values('%s', '%s', '%s','%s')"
    insert_into_teacher_borrow = "Insert into teacher_borrow values('%s', '%s', '%s','%s')"
    insert_into_book = "INSERT INTO book VALUES('%s', '%s', '%s','%s','%s')"
    delete_book_record = "delete from book where b_id = '%s'"
    show_all_books = "select * from book"
    show_book_id_stu = "select sb_id, sb_date,sb_return from student_borrow where sb_bid ='%s'"
    show_book_id_teach = "select tb_id, tb_date,tb_return from teacher_borrow where tb_bid ='%s'"
    return_book_stu = "update student_borrow set sb_return = 1 where sb_id = '%s' and sb_bid = '%s'"
    login_student = "select stu_id, stu_pwd from student where stu_id = '%s'"
    show_student_record = "select b_id, b_title, sb_date, sb_return from student_borrow join book on sb_bid = b_id where sb_id = '%s'"
    delete_book_id_teach = "select tb_return from teacher_borrow where tb_bid ='%s'"
    delete_book_id_stu = "select sb_return from student_borrow where sb_bid ='%s'"
    show_all_students = "select * from student"
    get_book_id = "select b_title from book where b_id = '%s'"
    insert_into_teacher = "INSERT INTO teacher VALUES('%s', '%s', '%s','%s','%s','%s')"
    show_all_teachers =  "select * from teacher"
    show_teacher_record = "select b_id, b_title, tb_date, tb_return from teacher_borrow join book on tb_bid = b_id where tb_id = '%s'"
    borrow_student_limit =  "select * from student_borrow where sb_id = '%s'"
    return_book_teach = "update teacher_borrow set tb_return = 1 where tb_id = '%s' and tb_bid = '%s'"
    borrow_teacher_limit =  "select * from teacher_borrow where tb_id = '%s'"

